{{- if eq "YES" .Values.configSecret.create  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-secret.name" . }}
  labels:
{{ include "sboot-service.labels" . | indent 4 }}
type: Opaque
stringData:
  application.properties: |-
{{- range $key, $value := .Values.configSecret.data }}
      {{ $key }}={{ $value  | toString }}
{{- end}}
  logback.xml: |-
{{- .Files.Get "resources/logback.xml" | nindent 6 }}

{{- end -}}
