{{- if eq "YES" .Values.dbSecret.create  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db-secret.name" . }}
  labels:
{{ include "sboot-service.labels" . | indent 4 }}
type: Opaque
data:
  postgresql-password : {{ index .Values.dbSecret "postgresql-password" | toString | b64enc | quote }}
  postgresql-user : {{ index .Values.dbSecret "postgresql-user"  | toString | b64enc | quote }}
  postgresql-host : {{ index .Values.dbSecret "postgresql-host"| toString | b64enc | quote }}
  postgresql-dbname: {{ index .Values.dbSecret "postgresql-dbname"| toString | b64enc | quote }}

{{- end -}}
